version: "2.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: semior/decompract:latest
    container_name: "decompract"
    hostname: "decompract"
    environment:
      DEBUG: '${DEBUG}'
      SERVICE_URL: '${SERVICE_URL}'
      SERVICE_PORT: '${SERVICE_PORT}'
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: ["/entrypoint.sh", "server"]
